name: Android App Releases
on:
  workflow_dispatch:
    inputs:
      upload_to_play:
        description: 'Upload AAB to Google Play'
        required: true
        default: true
        type: boolean
      publish_github_release:
        description: 'Publish GitHub release'
        required: true
        default: true
        type: boolean
      mark_prerelease:
        description: 'Mark as prerelease'
        required: true
        default: false
        type: boolean
      play_track:
        description: 'Google Play track'
        required: true
        default: 'production'
        type: choice
        options: [none, internal, alpha, beta, production]
      bump_type:
        description: 'Version bump type'
        required: true
        default: "patch"
        type: choice
        options:
          - none
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: mlm-games/ci/.github/workflows/android-release.yml@v1
    with:
      publish-release: ${{ inputs.publish_github_release }}
      app-name: Fluffy
      app-slug: fluffy
      application-id: app.fluffy
      play-track: ${{ inputs.upload_to_play && inputs.play_track || 'none' }}
      bump-type: ${{ inputs.bump_type }}
      prerelease: ${{ inputs.mark_prerelease }}
    secrets:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
